# Generated by Django 4.2.7 on 2023-12-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_parametr_goods_parametr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='имя категорії'),
        ),
    ]
